name: 'set-env'
description: 'Programmatically set global environment variables that can be used in subsequent steps'
author: 'Allen Evans'
branding:
  icon: 'globe'
  color: 'green'
runs:
  using: 'node12'
  main: 'dist/set-env.js'
